name: 'last-successful-build-action'
description: 'Action to find the SHA of the last successful workflow of a branch.'
author: 'Samhammer AG & Crystallize API'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
    required: true
  branch:
    description: 'Branch for the workflow to look for.'
    required: true
  workflow:
    description: 'Workflow name to look for.'
    required: false
  verify:
    description: 'Verify SHA of workflow run commit against list of commit SHAs in repository'
    required: false
    default: 'false'
  fallback:
    description: 'Fallback value if we are unable to determine the SHA of a successful run. Defaults to SHA of current commit.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
