name: 'last-successful-build-action'
description: 'Action to find the SHA of the last successful workflow of a branch.'
author: 'Samhammer AG & Crystallize API'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
    required: true
  branch:
    description: 'Name of the branch to load CI runs for. When tagsOnly is set to true, this value will be ignored when looking for the latest previous tag.'
    required: true
  workflow:
    description: 'Name of the workflow to load CI runs for.'
    required: false
  verify:
    description: 'Verify SHA of workflow run commit against list of commit SHAs in repository'
    required: false
    default: 'false'
  fallback:
    description: 'Fallback value if we are unable to determine the SHA of a successful run. Defaults to "origin/main", or to latest non ignored tag if tagsOnly is set to true.'
    required: false
  tagsOnly:
    description: 'Only look for CI runs for tags'
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'
